### ISSUE TITLE
error when destroying record

### ISSUE THREAD

**Issue by francescob** [sedubois/mobility-actiontext#3]
Hello, I have a strange error happening when destroying a record of my model that uses the :action_text backend, inserting and updating records works very well.

here's the relevant code in the model:

```
  extend Mobility
  translates :question, backend: :action_text
  translates :answer, backend: :action_text
```

and in the controller, very easy:

```
  def destroy
    @faq.destroy
    respond_with(:admin, @faq)
  end
```

that brings to the error:

```
PG::UndefinedColumn: ERROR:  column mobility_text_translations.record does not exist
LINE 1: ...ations".* FROM "mobility_text_translations" WHERE "mobility_...

```

the strange thing is that looking at the stack trace I see these line:

```
mobility (1.1.1) lib/mobility/backends/active_record/key_value.rb:198:in `block (3 levels) in <class:KeyValue>'
mobility (1.1.1) lib/mobility/backends/active_record/key_value.rb:198:in `block (2 levels) in <class:KeyValue>'
activesupport (6.0.3.5) lib/active_support/callbacks.rb:428:in `block in make_lambda'

```

so it looks like when destroying records is using the key_value backend instead of the action_text one.
Am I missing something in my configuration or is that a bug?

**Comment by arusa** [comment]
I successfully implemented this gem, but when I wrote my tests I realized the same error message when destroying objects:

```
ActiveRecord::StatementInvalid: PG::UndefinedColumn: ERROR:  column mobility_text_translations.record does not exist
LINE 1: ...ations".* FROM "mobility_text_translations" WHERE "mobility_...
```

**Comment by francescob** [comment]
I ended up adding that record column on mobility_text_translations table, it's completely useless, but at least it works

**Comment by sedubois** [comment]
Indeed the Action Text backend is an extension of the Key-Value backend. Also see info in the README [implementation note](https://github.com/sedubois/mobility-actiontext/#implementation-note). I haven't needed to delete such records in my app yet, so it's quite possible there are bugs. Don't hesitate to propose a PR with tests!

This is the code in Mobility:
https://github.com/shioyama/mobility/blob/687726d4bab774067da29efc7ade311a71260dcb/lib/mobility/backends/active_record/key_value.rb#L194-L200

It was written by @shioyama [in this PR](https://github.com/shioyama/mobility/pull/487). @shioyama any idea why it's `[translation_class, *Mobility::Backends::ActiveRecord::KeyValue::Translation.descendants].uniq`? In the case of Action Text should it not be something like `[translation_class, *translation_class.descendants].uniq`?

**Comment by Tranxuanvu** [comment]
I got the same problem, can you guys have a solution for this case?

**Comment by shioyama** [comment]
The reason it's `*Mobility::Backends::ActiveRecord::KeyValue::Translation.descendants].uniq` is so that if you define your own translation classes subclassing `Mobility::Backends::ActiveRecord::KeyValue::Translation`, e.g. a translation class for an integer translation, it would still correctly destroy those records.

That code destroy should probably be put behind an option that is default on so that ActionText can disable it.
