### ISSUE TITLE
No plugin configured for these keys: type. (Mobility::Pluggable::InvalidOptionKey)

### ISSUE THREAD

**Issue by leoplct** [sedubois/mobility-actiontext#51]
I got this error just after installing the gem

% rails c
```
/Users/name/.rvm/gems/ruby-3.1.2/gems/mobility-1.2.9/lib/mobility/pluggable.rb:51:in `validate_options': No plugin configured for these keys: type. (Mobility::Pluggable::InvalidOptionKey)
from /Users/name/.rvm/gems/ruby-3.1.2/gems/mobility-1.2.9/lib/mobility/plugins/backend.rb:100:in `validate_options'
```

**guide.rb**
```
class Guide < ApplicationRecord
  belongs_to :category
  extend Mobility
  translates :title, type: :string, locale_accessors: I18n.available_locales
  translates :content, type: :text, locale_accessors: I18n.available_locales, backend: :action_text
end
```

**Gemfile**
`gem "mobility-actiontext", "~> 1.1"`

**Comment by sedubois** [comment]
Could you remove the extra params and try again?

```diff
class Guide < ApplicationRecord
  extend Mobility
  ...
-  translates :content, type: :text, locale_accessors: I18n.available_locales, backend: :action_text
+  translates :content, backend: :action_text
end
```

**Comment by leoplct** [comment]
Yes, it works. I suggest adding it to the documentation because it was added from reading the Mobility's doc.
